spring.application.name=moviedb

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# limita o tamanho maximo da pagina (evita size=1000000)
spring.data.web.pageable.max-page-size=100
